name: Build and upload artifact

on: [ push, pull_request ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1.13.0
      - name: Set up MSVC
        run: |
          "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
        shell: cmd
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Meson and Ninja via pip
        run: |
          python -m pip install --upgrade pip
          pip install meson ninja
      - name: Configure and build with Meson
        run: |
          meson setup build64 --buildtype=release
          ninja -C build64
      - name: Create bin directory
        run: |
          mkdir bin
      - name: Copy to bin directory
        run:
          copy build64\mcardreader.dll bin\mcardreader.dll
          copy dist\qr_code.json bin\qr_code.json
      - name: Archive bin directory
        uses: actions/upload-artifact@v4
        with:
          name: mcardreader
          path: bin